version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python consumer.py"
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

#  dockerhost:
#    image: qoomon/docker-host
#    cap_add:
#      - NET_ADMIN
#      - NET_RAW
#    restart: on-failure
#    networks:
#      - backend
#
#  tcp_message_emitter:
#    image: alpine
#    depends_on:
#      - dockerhost
#    command: [ "sh", "-c", "while :; do date; sleep 1; done | nc 'dockerhost' 2323 -v"]
#    networks:
#      - backend
#
#networks:
#  backend:
#    driver: bridge
